# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-02 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20160802_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='length',
        ),
    ]
